<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../TalentCampus.Application/TalentCampus.Application.csproj" />
    <ProjectReference Include="../TalentCampus.Core/TalentCampus.Core.csproj" />
    <ProjectReference Include="../TalentCampus.Institutions.Talent/TalentCampus.Institutions.Talent.csproj" />
    <ProjectReference Include="../../runtime/src/Institutions/AethericForge.Runtime.Institutions.Abstractions/AethericForge.Runtime.Institutions.Abstractions.csproj" />
    <ProjectReference Include="../../runtime/src/Institutions/AethericForge.Runtime.Institutions.Campus/AethericForge.Runtime.Institutions.Campus.csproj" />
    <ProjectReference Include="../../runtime/src/Models/AethericForge.Runtime.Models/AethericForge.Runtime.Models.csproj" />
  </ItemGroup>

</Project>
